<?php 
$title = "Login";
$this->headtitle($title);

$form->setAttribute('action', $this->url('user/login'));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="container">
	<div class="row">
		<div class="col-sm-6">
        	<img class="mb-4" src="<?= $this->basePath('img/cityseal.png') ?>" alt="" width="72" height="72">
        	<h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        	<div class="form-group">
				<?php echo $this->formRow($form->get('SECURITY')); ?>
			</div>
        	<div class="form-group">
				<?php echo $this->formRow($form->get('USERNAME')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('PASSWORD')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('SUBMIT')); ?>
			</div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag($form); ?>