<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Welcome to<br>Middletown Workouts & Wellness</h1>
</div>
<?php if (! $this->currentUser()) : ?>
<div class="card-deck">
    <div class="card">
        <h2 class="card-header">Login</h2>
        <div class="card-body">
            <?php echo $this->partial('application/login', ['form' => $this->form]); ?>
        </div>
    </div>
</div>

<?php else : ?>
<iframe src="https://middletownct.app.box.com/embed/s/gbegf8e7w7hrd5apj52g2yooh41d5rbz?sortColumn=date&view=list" width="100%" height="100%" frameborder="0" allowfullscreen webkitallowfullscreen msallowfullscreen></iframe>
<?php endif; ?>

