<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Welcome to<br>Middletown Wellness Workouts</h1>
</div>
<?php if (! $this->currentUser()) : ?>
<div class="card-deck">
    <div class="card">
        <h2 class="card-header">Login</h2>
        <div class="card-body">
        <?php 
            $title = "Login";
            $this->headtitle($title);
            
            $form->setAttribute('action', $this->url('user/login'));
            $form->prepare();
            
            echo $this->form()->openTag($form);
            ?>
            
            <div class="container">
            	<div class="row">
            		<div class="col-sm-6">
                    	<img class="mb-4" src="<?= $this->basePath('img/cityseal.png') ?>" alt="" width="72" height="72">
                    	<h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
                    	<div class="form-group">
            				<?php echo $this->formRow($form->get('SECURITY')); ?>
            			</div>
                    	<div class="form-group">
            				<?php echo $this->formRow($form->get('USERNAME')); ?>
            			</div>
            			<div class="form-group">
            				<?php echo $this->formRow($form->get('PASSWORD')); ?>
            			</div>
            			<div class="form-group">
            				<?php echo $this->formRow($form->get('SUBMIT')); ?>
            			</div>
                    </div>
                </div>
            </div>
            <?php echo $this->form()->closeTag($form); ?>
        </div>
    </div>
</div>

<?php else : ?>
<iframe src="https://middletownct.app.box.com/embed/s/gbegf8e7w7hrd5apj52g2yooh41d5rbz?sortColumn=date&view=list" width="100%" height="100%" frameborder="0" allowfullscreen webkitallowfullscreen msallowfullscreen></iframe>
<?php endif; ?>

