<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="row">
	<div class="col-md-8">
        <div class="jumbotron">
            <h1 class="display-4">Welcome to<br>Middletown Workouts &amp; Wellness</h1>
        </div>
        <?php if (! $this->currentUser()) : ?>
        <div class="card-deck">
            <div class="card">
                <h2 class="card-header">Login</h2>
                <div class="card-body">
                    <?php echo $this->partial('application/login', ['form' => $this->form]); ?>
                </div>
            </div>
        </div>
        
        <?php else : ?>
        <iframe src="https://middletownct.app.box.com/embed/s/gbegf8e7w7hrd5apj52g2yooh41d5rbz?sortColumn=date&view=list" width="100%" height="100%" frameborder="0" allowfullscreen webkitallowfullscreen msallowfullscreen></iframe>
        <?php endif; ?>
	</div>
	<div class="col-md-4">
	<h1 class="mb-4">News</h1>
		<img class="mb-4" style="width: 300px; height: 225px;" src="<?=$this->basePath('img/image.jpg') ?>">
		<h4><?=$this->news['TITLE']?></h4>
		<?=$this->news['BODY']?>
        <p><small style="color: red;"><?=$this->news['DISCLAIMER']?></small></p>
	</div>
</div>